stages:
  - build
  - test 

## Build Stage ##
build-code:
  stage: build
  tags:
    - sh_snyk
  script:
    - echo "==== Project Building Started ====="
    - mvn clean install
    - echo "code build Successfull..."
    - ls
  artifacts:
    paths:
      - target/*.war
  


## SNYK Scanning

dependency_scanning:
  image: node:latest
  stage: test
  script:
    # Install npm, snyk, and snyk-to-html
    - npm install -g npm@latest
    - npm install -g snyk
    - npm install snyk-to-html -g
    # Run snyk help, snyk auth, snyk monitor, snyk test to break build and out report
    - snyk --help
    - snyk auth $SNYK_AUTH
    - snyk monitor --project-name=Gitlab-snyk
    - snyk test --json | snyk-to-html -o snyk_results.html
 
  # Save report to artifacts
  artifacts:
    when: always
    paths: 
      - snyk_results.html



